### ISSUE TITLE
Mod is not working when Towerfall is not installed on C: drive

### ISSUE THREAD

**Issue by PeGroe** [TowerfallAi/towerfall-ai#1]
When Towerfall is not installed on the C: drive the mod seems not to work. My installation was on D: and I got the following error output when trying to start the game via one of the provided python scripts:

![2023-08-22_14h59_27](https://github.com/TowerfallAi/towerfall-ai/assets/26149338/24b7b305-a224-469c-9e82-1a5cea29f8f8)

Afterwards I moved the installation to C: and everything worked fine.

**Comment by vcanaa** [comment]
Thanks for raising the issue @PeGroe.

I improved the error message and added an option to define the installation path with an environment variable. In your case, if you installed Towerfall in *D:/Program Files (x86)/Steam/steamapps/common/TowerFall*:

```
set TOWERFALL_PATH="D:/Program Files (x86)/Steam/steamapps/common/TowerFall"
```

Even better, set the env variable to your account, so you won't have to set it again:

```
setx TOWERFALL_PATH "D:/Program Files (x86)/Steam/steamapps/common/TowerFall"
```
